# Generated by Django 4.2.4 on 2023-08-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="شماره موبایل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                max_length=64, unique=True, verbose_name="آدرس الکترونیک"
            ),
        ),
    ]
