# Generated by Django 4.2.4 on 2023-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_managers_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verify",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="نام"
            ),
        ),
    ]
