# Generated by Django 4.2.4 on 2023-09-05 11:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_email_verify_user_verify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                max_length=64, unique=True, verbose_name="نشانی ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verify",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="توکن",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 9, 5, 15, 43, 15, 894905, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="تاریخ انقضا",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
    ]
