# Generated by Django 4.2.4 on 2023-09-08 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_user_username_alter_user_verify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 11, 46, 21, 547406, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضا",
            ),
        ),
    ]
