# Generated by Django 4.2.4 on 2023-09-08 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_passwordresettoken_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 20, 59, 22, 81167, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضا",
            ),
        ),
    ]
