# Generated by Django 4.2.4 on 2023-09-10 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_passwordresettoken_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 10, 11, 52, 19, 292490, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضا",
            ),
        ),
    ]
