# Generated by Django 4.2.4 on 2023-09-10 15:42

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_alter_passwordresettoken_expired_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="Date of birth"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="img/profile",
                verbose_name="Profile image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="melli",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 10, 19, 42, 26, 515251, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضا",
            ),
        ),
    ]
