# Generated by Django 4.2.4 on 2023-09-08 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Website address",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=128, verbose_name="نام\u200cکاربری"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="گذرواژه")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("h", "Hard"), ("g", "Good"), ("w", "Weak")],
                        default="g",
                        max_length=8,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("e", "ایمیل"), ("p", "Phone")],
                        default="e",
                        max_length=8,
                        verbose_name="Username type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "melli",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Melli code"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passwords",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "گذرواژه",
                "verbose_name_plural": "رمز ها",
            },
        ),
    ]
