# Generated by Django 4.2.4 on 2023-09-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0002_alter_password_address_alter_password_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="c_number",
            field=models.CharField(max_length=19, verbose_name="شماره کارت"),
        ),
    ]
