# Generated by Django 4.2.4 on 2023-09-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0003_alter_card_c_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="bank",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="بانک"
            ),
        ),
    ]
