# Generated by Django 4.2.4 on 2023-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0004_alter_card_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is archived"),
        ),
        migrations.AddField(
            model_name="password",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is archived"),
        ),
    ]
