# Generated by Django 4.2.4 on 2023-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0005_card_is_archived_password_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="بایگانی شده"),
        ),
        migrations.AlterField(
            model_name="password",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="بایگانی شده"),
        ),
    ]
